### ISSUE TITLE
Can't use SurblChecker without adding url prefix.

### ISSUE THREAD

**Issue by benigls** [fmarani/spam#2]
Importing and creating new instance of SurblChecker

```
>>> from spam.surbl import SurblChecker
>>> checker = SurblChecker()
```

Can't use SurblChecker without adding url prefix. It's giving me a `IndexError: list index out of range` error.

```
>>> checker.is_spam('google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spam/surbl.py", line 81, in is_spam
    return self.check_url(url) == self.IS_SPAM
  File "/usr/local/lib/python2.7/dist-packages/spam/surbl.py", line 67, in check_url
    return self.check_domain(domain)
  File "/usr/local/lib/python2.7/dist-packages/spam/surbl.py", line 75, in check_domain
    name_to_check = self._extract_registered_name(domain)
  File "/usr/local/lib/python2.7/dist-packages/spam/surbl.py", line 50, in _extract_registered_name
    pos = self._binary_search(self._two_list, components[-2] + "." + components[-1] + "\n")
IndexError: list index out of range
```

I have to add url prefix to make it work.

```
>>> checker.is_spam('http://google.com')
False
```

**Comment by fmarani** [comment]
that's the way that function works: uses urlparse to parse complete urls (not just the domain)

if you want to skip that step, you can do something like:

`>>> checker.check_domain("google.com") == checker.IS_SPAM`

**Comment by webbrain-one** [comment]
Thanks for reporting this! I opened https://github.com/fmarani/spam/pull/3 to fix it. It makes `SurblChecker` work with bare domains like `checker.is_spam('google.com')` without requiring a URL prefix, avoiding the `IndexError`.
